### ISSUE TITLE
 Error: Currenty there is no connection to the server.  reconnecting in 10

### ISSUE THREAD

**Issue by nishanth6** [johnnymast/mysql_websocket_chat#28]
As I'm using xampp server

**config.php**

`<?php
date_default_timezone_set('EUROPE/AMSTERDAM');

define ('DATABASE_HOST', 'localhost');
define ('DATABASE_USERNAME', 'root');
define ('DATABASE_PASSWORD', '');
define ('DATABASE_DB', 'socket_chat');
define ('ENABLE_DATABASE', true);

/**
 * The host can either be an IP or a hostname
 * on this machine. The port is just the port
 * plain and simple.
 */
define('CHAT_SERVER_HOST', '127.0.0.1');
define('CHAT_SERVER_PORT', '80');

`
I tried to run aa

http://localhost/chat/chat/index.php

Got the Error as 

>  Error: Currenty there is no connection to the server. 
> reconnecting in 10

**Comment by nishanth6** [comment]
@johnnymast 
Yes, I had xammp server running with MySQL. and I also imported the DB and in config 
define ('ENABLE_DATABASE', true);

**Comment by johnnymast** [comment]
Maybe you should switch off the database (for now) and try again to eliminate possible errors.

**Comment by johnnymast** [comment]
Alright i have spotted the error.

1. change CHAT_SERVER_PORT back to 8080
2. Set XAMPP up and point it to the directory with index.php
3. On the command line start php ./server.php

This will run index.php from xampp, this creates html and will connect to the server on port 8080. So server.php will bind to port 8080.

**Comment by nishanth6** [comment]
![capture](https://user-images.githubusercontent.com/26716038/46453010-aa50c800-c7bc-11e8-8c2f-1f2f296c045f.JPG)

No Good it didn't solved the problem

**Comment by johnnymast** [comment]
Is your version on github ?

**Comment by johnnymast** [comment]
This issue will be resolved in version 1.4. For now remove the prefix / from the local script and css links in the html and you will be good to go. 

Happy coding ! :octocat: 👍
