### ISSUE TITLE
Websocket configuration defines should be renamed because it's causing confusion.

### ISSUE THREAD

**Issue by johnnymast** [johnnymast/mysql_websocket_chat#32]
CHAT_SERVER_HOST and CHAT_SERVER_PORT should be renamed to WEBSOCKET_SERVER_HOST and WEBSOCKET_SERVER_PORT. Users seem to think this is for the HTTP part of the chat.

Also the README..MD should document using "php -S 127.0.0.1:2000"/

This issue was created because of github user @fahid744 had some problems getting the project up and running.

https://github.com/johnnymast/mysql_websocket_chat/blob/e5b96559fd3015d978488385b9dd17f4da170325/includes/config.php#L15-L16

**Comment by fahid744** [comment]
Good Work

**Comment by johnnymast** [comment]
@fahid744 I have updated the code and the README.md file. 

see https://github.com/johnnymast/mysql_websocket_chat/blob/v1.4/README.md

**Comment by johnnymast** [comment]
Issue closed.
