### ISSUE TITLE
save chat history on db and remove faker

### ISSUE THREAD

**Issue by adalenv** [johnnymast/mysql_websocket_chat#5]

**Comment by johnnymast** [comment]
Hey @adalenv,

Actually i think faker could be moved to a dev dependentie instead of a real dependentie. As for the  database part. It could be a good new feature.

**Comment by adalenv** [comment]
yes
i will work on design

**Comment by johnnymast** [comment]
If you want to make it your self i will accept pr's

**Comment by adalenv** [comment]
done

**Comment by johnnymast** [comment]
New versions will be.

Faker 1.7.1
cboden/ratchet v0.4.1

Im not move Faker to dev requirement. This is because this project is a skeleton and if you create a new project from this skeleton it will probably not install Faker winch crashes the server (not 100% sure).

**Comment by johnnymast** [comment]
If you wish to help you can test the 1.3 branch with new features. See this list
https://github.com/johnnymast/mysql_websocket_chat/blob/1.3/CHANELOG.md

**Comment by adalenv** [comment]
its released?

**Comment by johnnymast** [comment]
Yes it is
